name: Build and Deploy

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      VITE_API_URL: ${{ secrets.VITE_API_URL }}
      STATIC_FILES_URL: ${{ secrets.STATIC_FILES_URL }}
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create .env file from secrets
        run: |
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> .env

      - name: Build
        run: npm run build

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known hosts
        run: ssh-keyscan -p 32008 -H 85.10.199.143 >> ~/.ssh/known_hosts

      - name: Deploy via rsync
        run: |
          rsync -avzO --no-perms --no-times -e "ssh -p 32008" ./dist/ dev1@85.10.199.143:/www/wwwroot/app-stage.dentelio.com
